services:
  - type: web
    name: time_calculator_api
    env: docker
    dockerfilePath: time-api/Dockerfile
    plan: free
    autoDeploy: true

  - type: web
    name: time_calculator_frontend
    env: docker
    dockerfilePath: time-frontend/Dockerfile
    plan: free
    autoDeploy: true